# This is a basic workflow to help you get started with Actions

name: Chromium-CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: GIT
        run: |
          sudo apt install git re2c ninja-build generate-ninja -y
          sudo git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          sudo export PATH:"$PATH:${HOME}/depot_tools"
          sudo source ~/.bashrc

      # Runs a set of commands using the runners shell
      - name: Chromium
        run: |
          sudo mkdir ~/chromium && cd ~/chromium
          sudo fetch --nohooks chromium
          cd src
          sudo ./build/install-build-deps.sh
          sudo gclient runhooks
          gn gen out/Default
          autoninja -C out/Default chrome
      - name: Upload
        uses: actions/upload-artifact@3
        with: 
          name: Build
          path: ./*
          
